version: 2
updates:
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 3

  - package-ecosystem: nuget
    directories:
      - /src/**
      - /tests/**
      - /tools/**
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    allow:
      - dependency-type: all
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /cloudfunctions/veyon-api
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5
