<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>VeyonCampus.Agent</AssemblyName>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Version>0.4.41</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VeyonCampus.Core/VeyonCampus.Core.csproj" />
    <Content Include="Assets/StudentDefaultWallpaper-v1.jpg"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
