<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>VeyonCampus.Agent</AssemblyName>
    <Version>0.4.27</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VeyonCampus.Core/VeyonCampus.Core.csproj" />
  </ItemGroup>
</Project>
