<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>VeyonCampus.Worker</AssemblyName>
    <Version>0.4.48</Version>
    <VeyonCampusIncludeInstaller>false</VeyonCampusIncludeInstaller>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationManifest Condition="$([MSBuild]::IsOSPlatform('Windows'))">app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VeyonCampus.Core/VeyonCampus.Core.csproj" />
  </ItemGroup>
</Project>
