-- Veyon Campus site business data for CloudBase PostgreSQL.
-- Raw installation IDs never enter PostgreSQL. The telemetry device table stores
-- only a daily HMAC digest, which cannot be linked across days.

CREATE TABLE public.admin_profiles (
    user_id varchar(64) PRIMARY KEY,
    display_name text NOT NULL,
    role text NOT NULL CHECK (role IN ('owner', 'admin', 'editor', 'viewer')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.campuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    region varchar(80) NOT NULL CHECK (length(btrim(region)) BETWEEN 1 AND 80),
    city varchar(80) NOT NULL CHECK (length(btrim(city)) BETWEEN 1 AND 80),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX campuses_status_updated_idx
    ON public.campuses (status, updated_at DESC, id DESC);
CREATE INDEX campuses_region_city_idx
    ON public.campuses (region, city, id DESC);

CREATE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$function$;

CREATE TRIGGER campuses_set_updated_at
BEFORE UPDATE ON public.campuses
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.telemetry_daily_devices (
    day_utc date NOT NULL,
    installation_digest char(64) NOT NULL
        CHECK (installation_digest ~ '^[A-F0-9]{64}$'),
    recorded_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (day_utc, installation_digest)
);

CREATE TABLE public.telemetry_daily_stats (
    day_utc date PRIMARY KEY,
    unique_devices integer NOT NULL DEFAULT 0 CHECK (unique_devices >= 0),
    heartbeat_signals bigint NOT NULL DEFAULT 0 CHECK (heartbeat_signals >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.telemetry_retention_state (
    id boolean PRIMARY KEY DEFAULT true CHECK (id),
    last_cleanup_utc date NOT NULL
);

INSERT INTO public.telemetry_retention_state (id, last_cleanup_utc)
VALUES (true, (timezone('UTC', now()))::date - 1);

CREATE FUNCTION public.record_telemetry_heartbeat(
    p_utc_day date,
    p_installation_digest text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    v_inserted integer;
BEGIN
    IF p_utc_day IS DISTINCT FROM (timezone('UTC', statement_timestamp()))::date THEN
        RAISE EXCEPTION 'heartbeat date must be the current UTC date';
    END IF;

    IF p_installation_digest !~ '^[A-F0-9]{64}$' THEN
        RAISE EXCEPTION 'invalid installation digest';
    END IF;

    INSERT INTO public.telemetry_daily_devices (day_utc, installation_digest)
    VALUES (p_utc_day, p_installation_digest)
    ON CONFLICT (day_utc, installation_digest) DO NOTHING;
    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    INSERT INTO public.telemetry_daily_stats (
        day_utc, unique_devices, heartbeat_signals, updated_at
    ) VALUES (
        p_utc_day, v_inserted, 1, now()
    )
    ON CONFLICT (day_utc) DO UPDATE SET
        unique_devices = public.telemetry_daily_stats.unique_devices + EXCLUDED.unique_devices,
        heartbeat_signals = public.telemetry_daily_stats.heartbeat_signals + 1,
        updated_at = now();

    UPDATE public.telemetry_retention_state
    SET last_cleanup_utc = p_utc_day
    WHERE id = true AND last_cleanup_utc < p_utc_day;

    IF FOUND THEN
        DELETE FROM public.telemetry_daily_devices
        WHERE day_utc < p_utc_day - 90;
        DELETE FROM public.telemetry_daily_stats
        WHERE day_utc < p_utc_day - 400;
    END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_telemetry_heartbeat(date, text)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_telemetry_heartbeat(date, text)
    TO service_role;

GRANT USAGE ON SCHEMA public TO authenticated, service_role;

REVOKE ALL ON TABLE public.admin_profiles FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.campuses FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.telemetry_daily_devices FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.telemetry_daily_stats FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.telemetry_retention_state FROM PUBLIC, anon, authenticated, service_role;

GRANT SELECT ON TABLE public.admin_profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campuses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campuses_id_seq TO authenticated;
GRANT SELECT ON TABLE public.telemetry_daily_stats TO authenticated;

GRANT ALL ON TABLE public.admin_profiles TO service_role;
GRANT ALL ON TABLE public.campuses TO service_role;
GRANT ALL ON TABLE public.telemetry_daily_devices TO service_role;
GRANT ALL ON TABLE public.telemetry_daily_stats TO service_role;
GRANT ALL ON TABLE public.telemetry_retention_state TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.campuses_id_seq TO service_role;

ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_daily_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_retention_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_profiles_read_self ON public.admin_profiles
    FOR SELECT TO authenticated
    USING (user_id = (SELECT auth.uid()));

CREATE POLICY campuses_read_site_admins ON public.campuses
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin', 'editor', 'viewer')
        )
    );

CREATE POLICY campuses_insert_editors ON public.campuses
    FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin', 'editor')
        )
    );

CREATE POLICY campuses_update_editors ON public.campuses
    FOR UPDATE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin', 'editor')
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin', 'editor')
        )
    );

CREATE POLICY campuses_delete_admins ON public.campuses
    FOR DELETE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin')
        )
    );

CREATE POLICY telemetry_stats_read_site_admins ON public.telemetry_daily_stats
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.admin_profiles AS profile
            WHERE profile.user_id = (SELECT auth.uid())
              AND profile.role IN ('owner', 'admin', 'editor', 'viewer')
        )
    );

INSERT INTO public.admin_profiles (user_id, display_name, role)
SELECT sub, COALESCE(NULLIF(name, ''), NULLIF(username, ''), '管理员'), 'owner'
FROM auth.users
WHERE project = 'veyon-control-d3gs8hmuyd09c00a7'
  AND username = 'administrator'
  AND created_from = 'admin'
  AND sub IS NOT NULL
ON CONFLICT (user_id) DO NOTHING;
